spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: productModule
            uri: lb://product
            predicates:
              - Path=/product/**
          - id: noteModule
            uri: lb://note
            predicates:
              - Path=/note/**
